export const CMS_RESOURCES = {
  gallery: {
    title: 'Gallery',
    subtitle: 'Manage media gallery items',
    endpoint: '/admin/cms/gallery',
    columns: [
      { field: 'title', header: 'Title' },
      { field: 'category', header: 'Category' },
      { field: 'isActive', header: 'Status' },
    ],
    fields: [
      { name: 'title', label: 'Title', required: true },
      { name: 'category', label: 'Category' },
      { name: 'imageUrl', label: 'Image URL' },
      { name: 'description', label: 'Description', multiline: true, rows: 3 },
      { name: 'order', label: 'Order', type: 'number' },
      { name: 'isActive', label: 'Active', type: 'checkbox' },
    ],
  },
  events: {
    title: 'Events',
    subtitle: 'Manage community events',
    endpoint: '/admin/cms/events',
    columns: [
      { field: 'title', header: 'Title' },
      { field: 'location', header: 'Location' },
      { field: 'isActive', header: 'Status' },
    ],
    fields: [
      { name: 'title', label: 'Title', required: true },
      { name: 'description', label: 'Description', multiline: true, rows: 4 },
      { name: 'location', label: 'Location' },
      { name: 'eventDate', label: 'Event Date', type: 'datetime-local' },
      { name: 'imageUrl', label: 'Image URL' },
      { name: 'isActive', label: 'Active', type: 'checkbox' },
    ],
  },
  blogs: {
    title: 'Blogs',
    subtitle: 'Manage blog posts',
    endpoint: '/admin/cms/blogs',
    columns: [
      { field: 'title', header: 'Title' },
      { field: 'author', header: 'Author' },
      { field: 'isPublished', header: 'Published', render: (r) => (r.isPublished ? 'Yes' : 'Draft') },
    ],
    fields: [
      { name: 'title', label: 'Title', required: true },
      { name: 'slug', label: 'Slug' },
      { name: 'author', label: 'Author' },
      { name: 'excerpt', label: 'Excerpt', multiline: true, rows: 2 },
      { name: 'content', label: 'Content', rich: true },
      { name: 'imageUrl', label: 'Image URL' },
      { name: 'isPublished', label: 'Published', type: 'checkbox' },
    ],
  },
  stories: {
    title: 'Success Stories',
    subtitle: 'Manage impact stories',
    endpoint: '/admin/cms/success-stories',
    columns: [
      { field: 'title', header: 'Title' },
      { field: 'category', header: 'Category' },
      { field: 'impact', header: 'Impact' },
    ],
    fields: [
      { name: 'title', label: 'Title', required: true },
      { name: 'category', label: 'Category' },
      { name: 'summary', label: 'Summary', multiline: true, rows: 2 },
      { name: 'content', label: 'Full Story', rich: true },
      { name: 'impact', label: 'Impact Label' },
      { name: 'color', label: 'Color', type: 'color' },
      { name: 'imageUrl', label: 'Image URL' },
      { name: 'isActive', label: 'Active', type: 'checkbox' },
    ],
  },
  faqs: {
    title: 'FAQ',
    subtitle: 'Manage frequently asked questions',
    endpoint: '/admin/cms/faqs',
    columns: [
      { field: 'question', header: 'Question' },
      { field: 'order', header: 'Order' },
    ],
    fields: [
      { name: 'question', label: 'Question', required: true },
      { name: 'answer', label: 'Answer', rich: true },
      { name: 'order', label: 'Order', type: 'number' },
      { name: 'isActive', label: 'Active', type: 'checkbox' },
    ],
  },
  notifications: {
    title: 'Notifications',
    subtitle: 'Push notification messages',
    endpoint: '/admin/cms/notifications',
    columns: [
      { field: 'title', header: 'Title' },
      { field: 'type', header: 'Type' },
      { field: 'targetRole', header: 'Target' },
    ],
    fields: [
      { name: 'title', label: 'Title', required: true },
      { name: 'message', label: 'Message', multiline: true, rows: 3 },
      { name: 'type', label: 'Type', select: ['info', 'success', 'warning', 'error'] },
      { name: 'targetRole', label: 'Target', select: ['all', 'customer', 'admin'] },
      { name: 'isActive', label: 'Active', type: 'checkbox' },
    ],
  },
  notices: {
    title: 'Notices',
    subtitle: 'Site-wide notice banners',
    endpoint: '/admin/cms/notices',
    columns: [
      { field: 'title', header: 'Title' },
      { field: 'priority', header: 'Priority' },
    ],
    fields: [
      { name: 'title', label: 'Title', required: true },
      { name: 'content', label: 'Content', rich: true },
      { name: 'priority', label: 'Priority', select: ['low', 'medium', 'high'] },
      { name: 'isActive', label: 'Active', type: 'checkbox' },
    ],
  },
  voices: {
    title: 'Voices of Hope',
    subtitle: 'Testimonials and quotes',
    endpoint: '/admin/cms/voices',
    columns: [
      { field: 'name', header: 'Name' },
      { field: 'role', header: 'Role' },
    ],
    fields: [
      { name: 'name', label: 'Name', required: true },
      { name: 'role', label: 'Role / Location' },
      { name: 'quote', label: 'Quote', multiline: true, rows: 4, required: true },
      { name: 'order', label: 'Order', type: 'number' },
      { name: 'isActive', label: 'Active', type: 'checkbox' },
    ],
  },
};
